version: '3'
services:
  inventanalytics-database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: inventanalytics
      MYSQL_DATABASE: inventanalytics
    ports:
      - '3306:3306'
    networks:
      - inventanalytics-network
  inventanalytics-adminer:
    image: adminer:latest
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: inventanalytics-database
    depends_on:
      - inventanalytics-database
    networks:
      - inventanalytics-network
  inventanalytics-server:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - inventanalytics-database
    networks:
      - inventanalytics-network
    env_file:
      - .env 
networks:
  inventanalytics-network:
    driver: bridge